image: node:16

stages:
    - install
    - build
    - deploy
cache:
    key: weixin
    paths:    
        - node_modules

job_install:
    stage: install
    tags: 
        - global-runner
    script:
        - npm install
job_build:
    stage: build
    script:
        - node --version
        - npm run build

job_deploy:
    stage: deploy
    script:
        - echo "start deploy"
