stages:
    - install
    - build
    - deploy
job_install:
    stage: install
    script:
        - npm install
job_build:
    stage: build
    script:
        - npm run build

job_deploy:
    stage: deploy
    script:
        - echo "start deploy"
